spring:
  datasource:
    url: jdbc:mysql://localhost:3306/corestaff
#    driverClassName: org.h2.Driver
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true